apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clean-disk-backend.yaml
  - clean-disk-frontend.yaml
  - clean-evicted-pods-rbac.yaml
  - clean-evicted-pods.yaml
  - metamodel-health-check-rbac.yaml
  - metamodel-health-check.yaml
