apiVersion: v1
kind: Service
metadata:
  name: predictions-intake
  namespace: myapp
  labels:
    app.kubernetes.io/name: predictions-intake
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: predictions-intake
  ports:
    - name: http
      port: 8082
      targetPort: http
  type: ClusterIP
