apiVersion: v1
kind: ResourceQuota
metadata:
  name: myapp-quota
  namespace: myapp
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  hard:
    requests.cpu: "8"
    limits.cpu: "16"

    requests.memory: "16Gi"
    limits.memory: "32Gi"

    persistentvolumeclaims: "10"
    requests.storage: "50Gi"

    pods: "50"
    services: "30"
    secrets: "50"
    configmaps: "30"
