apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
  namespace: myapp
data:
  definitions.json: |
    {
      "vhosts": [
        { "name": "/" }
      ],
      "users": [
        {
          "name": "rabbitmq",
          "password": "rabbitmq",
          "tags": "administrator"
        },
        {
          "name": "myapp",
          "password_hash": "LexKrGJIePrQZUzqDG0fPJpcUe0Tm8NwBQ8nnJVThGw6DWO1",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "rabbitmq",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "myapp",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [
        { "name": "subscription_updates_queue", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} },
        { "name": "user_notifications_queue", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} },
        { "name": "direct_submissions_queue", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} },
        { "name": "kpi.prediction.received", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {} }
      ],
      "exchanges": [
        { "name": "direct_submissions_exchange", "vhost": "/", "type": "direct", "durable": true, "auto_delete": false, "internal": false, "arguments": {} },
        { "name": "payment.events", "vhost": "/", "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {} },
        { "name": "kpi.events", "vhost": "/", "type": "topic", "durable": true, "auto_delete": false, "internal": false, "arguments": {} }
      ],
      "bindings": [
        { "source": "direct_submissions_exchange", "vhost": "/", "destination": "direct_submissions_queue", "destination_type": "queue", "routing_key": "direct_submissions_rk", "arguments": {} },
        { "source": "payment.events", "vhost": "/", "destination": "subscription_updates_queue", "destination_type": "queue", "routing_key": "subscription.updates", "arguments": {} },
        { "source": "payment.events", "vhost": "/", "destination": "user_notifications_queue", "destination_type": "queue", "routing_key": "user.notifications", "arguments": {} },
        { "source": "kpi.events", "vhost": "/", "destination": "kpi.prediction.received", "destination_type": "queue", "routing_key": "prediction.received", "arguments": {} }
      ]
    }
