apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/ingress.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - user-management/deployment.yaml
  - user-management/service.yaml
  - user-management/ingress.yaml
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - payment-service/ingress.yaml
