apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/ingress.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - user-management/deployment.yaml
  - user-management/service.yaml
  - user-management/user-service.yaml
  - user-management/ingress.yaml
  - user-management/secret.yaml
  # stripe-credentials: créer manuellement (kubectl create secret generic stripe-credentials ...)
  - payment-service/deployment.yaml
  - payment-service/service.yaml
  - payment-service/ingress.yaml
  - crm-client/deployment.yaml
  - crm-client/service.yaml
  - crm-client/ingress.yaml
  - predictions-intake/deployment.yaml
  - predictions-intake/service.yaml
  - predictions-intake/ingress.yaml
  - chatbot/secret.yaml
  - chatbot/deployment.yaml
  - chatbot/service.yaml
  - chatbot/ingress.yaml
  - kpi-dashboard/deployment.yaml
  - kpi-dashboard/service.yaml
  - kpi-dashboard/ingress.yaml
  - ingress-ip.yaml
