apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: myapp
  labels:
    app: consul
spec:
  replicas: 0  # remis à 1 après vidage des serveurs
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      nodeSelector:
        kubernetes.io/hostname: frontend-vm
      containers:
        - name: consul
          image: hashicorp/consul:1.17
          args:
            - agent
            - -server
            - -bootstrap-expect=1
            - -retry-join=consul.myapp.svc.cluster.local
            - -ui
            - -client=0.0.0.0
            - -data-dir=/consul/data
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              protocol: UDP
              name: dns
          resources:
            requests:
              memory: "384Mi"
              cpu: "200m"
            limits:
              memory: "640Mi"
              cpu: "500m"
          startupProbe:
            exec:
              command:
                - consul
                - info
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - consul
                - info
            initialDelaySeconds: 0
            periodSeconds: 15
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - consul
                - info
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 10
