apiVersion: v1
kind: Secret
metadata:
  name: mail-credentials
  namespace: myapp
  labels:
    app: user-management
type: Opaque
stringData:
  SPRING_MAIL_USERNAME: "mailer@example.com"
  SPRING_MAIL_PASSWORD: "REDACTED_MAIL_PW"
