apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-default-deny.yaml
  - 10-allow-dns.yaml
  - 20-allow-traefik-ingress.yaml
  - 30-allow-gateway-to-backends.yaml
  - 40-allow-backends-to-postgres.yaml
  - 41-allow-backends-egress-postgres.yaml
  - 50-allow-redis-access.yaml
  - 60-allow-rabbitmq-access.yaml
  - 70-allow-consul-access.yaml
  - 80-allow-minio-access.yaml
  - 90-allow-monitoring.yaml
  - 95-allow-external-egress.yaml
  - 98-allow-argocd.yaml
