apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myapp

resources:
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - postgres/init-databases-job.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - consul/deployment.yaml
  - consul/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
