# deploy/k8s/infra/monitoring/prometheus-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: myapp
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
  type: ClusterIP