apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: myapp
  labels:
    app: statsd-exporter
spec:
  selector:
    app: statsd-exporter
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
      protocol: TCP
    - name: statsd-udp
      port: 9125
      targetPort: 9125
      protocol: UDP
  type: ClusterIP
