# Ingress API Gateway — k3s utilise Traefik par défaut
# Adapter le host selon ton domaine (ex: api.myapp.com)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-client
  namespace: myapp
  labels:
    app: crm-client
spec:
  ingressClassName: traefik
  rules:
    - host: crm.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-client
                port:
                  number: 8083
