---
all:
  vars:
    ansible_user: myapp
    ansible_ssh_private_key_file: "~/.ssh/myapp_vms"
  children:
    k3s_server:
      hosts:
        backend-vm:
          ansible_host: 10.0.0.11
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -i ~/.ssh/myapp_vms myapp@203.0.113.10"'
    k3s_agents:
      hosts:
        frontend-vm:
          ansible_host: 203.0.113.10
        backend2:
          ansible_host: 10.0.0.13
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null -i ~/.ssh/myapp_vms myapp@203.0.113.10"'
    jumphost:
      hosts:
        frontend-vm:
