apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metamodel-modules-pvc
  namespace: myapp
  labels:
    app.kubernetes.io/name: metamodel-orchestration
    app.kubernetes.io/component: pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
