apiVersion: v1
kind: Service
metadata:
  name: metamodel-orchestration
  namespace: myapp
  labels:
    app.kubernetes.io/name: metamodel-orchestration
    app.kubernetes.io/component: pipeline
spec:
  selector:
    app.kubernetes.io/name: metamodel-orchestration
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
