apiVersion: v1
kind: Service
metadata:
  name: metamodel-orchestration
  namespace: myapp
  labels:
    app: metamodel-orchestration
spec:
  selector:
    app: metamodel-orchestration
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP

