apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metamodel-orchestration-static-ingress
  namespace: myapp
  labels:
    app: metamodel-orchestration
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: myapp-airflow-static-strip-prefix@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - airflow.dev.example.com
      secretName: dev-myapp-io-tls
  rules:
    - host: "airflow.dev.example.com"
      http:
        paths:
          - path: /api/v2/static
            pathType: Prefix
            backend:
              service:
                name: metamodel-orchestration
                port:
                  name: ui-static
