apiVersion: v1
kind: Service
metadata:
  name: chatbot
  namespace: myapp
  labels:
    app.kubernetes.io/name: chatbot
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: chatbot
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
